name: Markdown lint
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - run: gem install mdl
      # lint ignoring the line length lint
      - run: mdl -r ~MD013 README.md
      - run: mdl -r ~MD013 docs/*
